"""add app state table

Revision ID: 6a033a2ce106
Revises: 7f694682ae68
Create Date: 2026-03-03 18:47:15.859773

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a033a2ce106"
down_revision: str | Sequence[str] | None = "7f694682ae68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appstate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_db_checked_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appstate")
    # ### end Alembic commands ###
