"""initial

Revision ID: 6cfd79ed8096
Revises:
Create Date: 2026-02-24 08:32:08.648901

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cfd79ed8096"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scanned_at", sa.DateTime(), nullable=False),
        sa.Column("image_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("grype_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("db_built", sa.DateTime(), nullable=True),
        sa.Column("distro_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("distro_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vulnerability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("vuln_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("urls", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cvss_base_score", sa.Float(), nullable=True),
        sa.Column("epss_score", sa.Float(), nullable=True),
        sa.Column("epss_percentile", sa.Float(), nullable=True),
        sa.Column("is_kev", sa.Boolean(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("cwes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("package_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("installed_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fixed_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fix_state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("package_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("package_language", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("purl", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vulnerability")
    op.drop_table("scan")
    # ### end Alembic commands ###
