"""add container_name to scan

Revision ID: 7f694682ae68
Revises: 899bb4e9ac6d
Create Date: 2026-02-26 15:31:35.152838

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f694682ae68"
down_revision: str | Sequence[str] | None = "899bb4e9ac6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scan", sa.Column("container_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scan", "container_name")
    # ### end Alembic commands ###
