"""Add Setting and SystemTask tables

Revision ID: f821d6764dee
Revises: 6672a2a27dc7
Create Date: 2026-03-08 18:55:38.895098

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f821d6764dee"
down_revision: str | Sequence[str] | None = "6672a2a27dc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scan_image_name"), table_name="scan")
    op.drop_index(op.f("ix_scan_scanned_at"), table_name="scan")

    op.drop_index(op.f("ix_vulnerability_scan_id_cvss"), table_name="vulnerability")
    op.drop_index(op.f("ix_vulnerability_scan_id_epss"), table_name="vulnerability")
    op.drop_index(op.f("ix_vulnerability_scan_id_first_seen"), table_name="vulnerability")
    op.drop_index(op.f("ix_vulnerability_scan_id_is_kev"), table_name="vulnerability")
    op.drop_index(op.f("ix_vulnerability_scan_id_severity"), table_name="vulnerability")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_vulnerability_scan_id_severity"), "vulnerability", ["scan_id", "severity"], unique=False)
    op.create_index(op.f("ix_vulnerability_scan_id_is_kev"), "vulnerability", ["scan_id", "is_kev"], unique=False)
    op.create_index(
        op.f("ix_vulnerability_scan_id_first_seen"), "vulnerability", ["scan_id", "first_seen_at", "id"], unique=False
    )
    op.create_index(
        op.f("ix_vulnerability_scan_id_epss"), "vulnerability", ["scan_id", "epss_score", "id"], unique=False
    )
    op.create_index(
        op.f("ix_vulnerability_scan_id_cvss"), "vulnerability", ["scan_id", "cvss_base_score", "id"], unique=False
    )
    op.create_index(op.f("ix_scan_scanned_at"), "scan", ["scanned_at"], unique=False)
    op.create_index(op.f("ix_scan_image_name"), "scan", ["image_name"], unique=False)
    # ### end Alembic commands ###
